site_name: pyptsca.github.io
theme:
  name: material
  #font: 
    #code: Courier New
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      # teal 
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black 
      accent: indigo
      # teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式
  language: zh

repo_url: https://github.com/PYPTsca/pyptsca.github.io/ # 右上角点击跳转的链接
repo_name: pyptsca.github.io # 右上角的名字

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - 主页: index.md
 - C++ 开发环境使用须知: C++ Developing enviornment use information.md
 - 计算机导论试卷答案:
    - 19y: paper/19.md
    - 21y: paper/21.md
    - 22y: paper/22.md
    - 23y: paper/23.md
    - 24y: paper/24.md
 - MKdocs中文教程:
    - MKdocs教程:
        - 0. Mkdocs教程前言: blog/Mkdocs/mkfirst.md
        - 1.利用Mkdocs部署静态网页: blog/Mkdocs/mkdocs1.md
        - 2.Mkdocs配置说明(mkdocs.yml): blog/Mkdocs/mkdocs2.md
        - 3. 解决 mkdocs部署 Github Pages 自定义域名失效的问题: blog/Mkdocs/mkdocs3.md
    - Mkdocs美化:
        - 为网站添加Google广告: blog/webSiteBeauty/GoogleAD.md
        - 添加相关推荐文章: blog/webSiteBeauty/recommend.md
        - 添加Mkdocs博客: blog/Mkdocs/mkdocsblog.md
        - MkDocs文档AI摘要: blog/webSiteBeauty/Mkdocs-AI-Summary.md
        - 添加阅读信息统计: blog/webSiteBeauty/reading_time.md
        - 网页圆角化设计: blog/webSiteBeauty/yuanjiaohua.md
        - 添加评论系统(giscus为例): blog/webSiteBeauty/mkcomments.md
        - 添加在线聊天: blog/webSiteBeauty/webtalknow.md
        - 添加友链: blog/webSiteBeauty/linktech.md
        - 添加顶部公告栏: blog/webSiteBeauty/header.md
        - 修改网站字体: blog/webSiteBeauty/mkdocsfont.md
        - JS实现鼠标样式: blog/webSiteBeauty/shubiao.md
        - 背景特效: blog/webSiteBeauty/backgroud.md
        - 添加404页面: blog/webSiteBeauty/404.md
        - 嵌入PDF文件: blog/webSiteBeauty/mkpdf.md
        - 相对地址的一些问题: blog/webSiteBeauty/Relativeaddress.md
        - 为MKdocs添加文章修订时间戳: blog/webSiteBeauty/time.md
        - 页脚设置: blog/webSiteBeauty/footer.md
        - 加速网站访问的一些心得: blog/webSiteBeauty/accelerate.md